#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  encoder,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           left,        tmotorVex393HighSpeed_HBridge, openLoop, driveLeft, encoderPort, I2C_1)
#pragma config(Motor,  port10,          right,        tmotorVex393HighSpeed_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define stdio.h;

float wheelRadius=5.1;//in cm
float ticksPerRev=392;
float ticksPerCm=ticksPerRev/(2.0*PI*wheelRadius);

float kP=-0.2;
float kD;
float kI;

float targetTicks, error;

//just kp
void moveStraightP(float cm){
	SensorValue[encoder]=0;

	targetTicks=cm*ticksPerCm;
	error=targetTicks-SensorValue[encoder];

	while(error!=0){

		motor[right]=kP*error;
		motor[left]=kP*error;
		error=targetTicks-SensorValue[encoder];
	}
	motor[left]=motor[right]=0;
}


//kp and kd


task main()
{
	moveStraightP(15);//in cm


}
