#pragma config(Sensor, dgtl1,  encoder,        sensorQuadEncoder)
#pragma config(Motor,  port1,           LDrive,          tmotorVex393HighSpeed_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,           RDrive,         tmotorVex393HighSpeed_MC29, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//all dimensions in cm
#define RIGHT = 0;
#define FORWD = 1;
#define LEFT = 2;
#define BACKWD = 3;

float wheelRadius=3.5*2.54;
float ticksPerRev=392;
float ticksPerCm=ticksPerRev/(2*PI*wheelRadius);
float axleLength=30;

void moveForward(float cm){
	motor[Left] = 127;
	motor[Right] = 127;

	while(SensorValue[encoder]<cm*ticksPerCm){
		wait1Msec(1);
	}
}

void turnRight(float radians){
	motor[Left]=-127;
	motor[Right]=127;

	while(SensorValue[encoder]<((2*PI*axleLength/2)*radians)*ticksPerCm){
		wait1Msec(1);
	}
}

void turnLeft(float radians){
	motor[Left]=127;
	motor[Right]=-127;

	while(SensorValue[encoder]<((2*PI*axleLength/2)*radians)*ticksPerCm){
		wait1Msec(1);
	}
}

task main()
{
	moveForward(50);
	turn(PI/((float)2));
	moveBackward(50);
	turn(PI/((float)2));
}
